[build]
  publish = "."

# Cache agressif pour tes assets
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Sécurité + referrer policy sur tout le site
[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Pas de cache pour les pages HTML
[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-cache"

[[headers]]
  for = "/merci.html"
  [headers.values]
  Cache-Control = "no-cache"
